### ISSUE TITLE
Application not working with JDK 9.0.1

### ISSUE THREAD

**Issue by pbougue** [CUTR-at-USF/gtfs-realtime-validator#312]
**Summary:** 

I tried to start locally the application with JDK 9.0.1, it crashed.

**Steps to reproduce:** 

On a local setup, try to launch using JDK 9.0.1 (Linux zip downloaded from Oracle website)

**Expected behavior:** 

Application running like it is running when using JDK 1.8.0_152 (obtained the same way) on my laptop.
This is not a big problem as there is an easy workaround, but still think it's good to trace it for people trying it later.

**Observed behavior:** 

Application crashing with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43)
        at org.hibernate.boot.MetadataSources.<init>(MetadataSources.java:87)
        at org.hibernate.cfg.Configuration.<init>(Configuration.java:123)
        at org.hibernate.cfg.Configuration.<init>(Configuration.java:118)
        at edu.usf.cutr.gtfsrtvalidator.hibernate.HibernateUtil.configureSessionFactory(HibernateUtil.java:19)
        at edu.usf.cutr.gtfsrtvalidator.Main.main(Main.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 6 more
```

**Platform:** 

Operating on Firefox 59 (nightly), Ubuntu 15.04, JDK 9.0.1 x64 (from Oracle website).

**Comment by barbeau** [comment]
@pbougue Thanks for reporting!  What's the workaround?

**Comment by pbougue** [comment]
My workaround was to run it on JDK 1.8.0_152 :)
Was easy to me, maybe not so free on every platform, though.

**Comment by barbeau** [comment]
Looks like this is caused by the new modular system in Java 9:
* https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j
* https://keyholesoftware.com/2017/06/19/migrating-to-java-9/

I'll see if I can give this a look.  From quickly skimming these pages, the project may build on Java 9 as-is using:

`mvn clean install -DargLine="--add-modules java.xml.bind"`

If that doesn't work, we may need to bump the versions of some dependencies (e.g., Hibernate) for post Java 9 releases too.  For example, `hibernate-core` is currently `5.2.2.Final` but `5.2.12.Final` is now available from Maven Central.

**Comment by barbeau** [comment]
So, after bumping the Maven plugin versions (I'll push this fix shortly), I'm able to run the project on Java 9 with the following:

`java -Djsee.enableSNIExtension=false --add-modules java.xml.bind -jar gtfs-realtime-validator-webapp/target/gtfs-realtime-validator-webapp-1.0.0-SNAPSHOT.jar`

This adds the missing JAXB classes in `java.xml.bind`.

To build the project you continue to use the normal `mvn package`.

**Comment by mpaine-act** [comment]
This workaround no longer works with JDK 11, as the --add-module argument was removed.   Can you add JAX-B APIs to the maven dependencies?  Then your nightly build should work for JDK 11.

**Comment by barbeau** [comment]
@mpaine-act Thanks for the heads up! What's the exact dependency, and will this still work back to JDK 8 with the JAXB dependency added in pom.xml?
